name: payungpribadi
description: "Payungpribadi clone app."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  google_fonts: ^4.0.3
  badges: ^3.1.2
  flutter_stepindicator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/home.svg
    - assets/icons/settings.svg
    - assets/icons/notifications.svg
    - assets/icons/cart.svg
    - assets/icons/coupon.svg
    - assets/icons/map.svg
    - assets/icons/transactions.svg
    - assets/icons/friends.svg
    - assets/icons/search.svg

